# Generated by Django 2.2.4 on 2022-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Uploadby',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='uploadbook', to='login.Users'),
        ),
    ]
